name: Deploy DB
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Check/Create S3 bucket for Terraform state
      - name: Ensure S3 bucket exists
        run: |
          bucket_name=my-s3-bucket-pos-tech-postgres
          region=${{ secrets.AWS_REGION }}
          if aws s3 ls "s3://$bucket_name" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Creating S3 bucket: $bucket_name"
            aws s3api create-bucket --bucket $bucket_name --region $region --create-bucket-configuration LocationConstraint=$region
            aws s3api put-bucket-versioning --bucket $bucket_name --versioning-configuration Status=Enabled
          else
            echo "S3 bucket already exists."
          fi

      - name: Terraform Format
        id: fmt
        run: terraform fmt check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="region=${{ secrets.AWS_REGION }}" -var="username=${{ secrets.DB_USERNAME }}" -var="password=${{ secrets.DB_PASSWORD }}"

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="region=${{ secrets.AWS_REGION }}" -var="username=${{ secrets.DB_USERNAME }}" -var="password=${{ secrets.DB_PASSWORD }}"

